---
- hosts: all
  vars:
    ruby: ruby-2.1.5
    root_db_password: password
  tasks:
    - name: make sure the system encoding is utf-8
      sudo: yes
      template: src=templates/locale dest=/etc/default/locale
                owner=root group=root mode=644

    - include: tasks/apt.yml
    - include: tasks/mysql.yml
    # - include: tasks/postgresql.yml
    - include: tasks/oh-my-zshell.yml
    - include: tasks/ruby.yml
    # - include: tasks/ember.yml

    - name: bundle install
      shell: 'executable=/bin/zsh chdir=/vagrant . "$HOME/.rvm/scripts/rvm" && rvm use --default {{ ruby }}'