---
- name: update apt
  apt: update_cache=yes
  sudo: yes

- name: install base packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - vim
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - npm
    - nodejs
    - libpq-dev
    - nfs-common

# - name: symlink node
#   shell: sudo ln -s /usr/bin/nodejs /usr/bin/node
#   register: result
