---
- name: add postgres repo
  shell: sudo sh -c "echo 'deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' > /etc/apt/sources.list.d/pgdg.list" && wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  
- name: install postgresql
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - postgresql-common
    - postgresql-9.3
    - libpq-dev

- name: create vagrant user on postgresql
  shell: sudo -u postgres createuser vagrant -s
